// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrongerNotificationApi.Infra.Persistence;

#nullable disable

namespace StrongerNotificationApi.Migrations
{
    [DbContext(typeof(StrongerNotifDbContext))]
    partial class StrongerNotifDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StrongerNotificationApi.Domain.Entities.UserDeviceEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte?>("TrainingDays")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("UserId", "DeviceToken");

                    b.ToTable("UserDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
